travis:
  secure:
    BINSTAR_TOKEN: Mk5wPIL93cnLtZniC259qOw3UnsYGlJAvPYhcyPDGcnEPBxXEIWUJRZ7S/jLzjT7hMUpxbrxv7KR1nuPAKwsr5KnqrcNDKNbb7cc+aRVFab6kjY+iFAx/e6nxfRGH5O+ifdjGXKrO0+r2YzhuhiNQRSQTAK44jXrMpdDZANH+23dLbvEutE5T4x242FQ1E9TDCgIfVChfxDkI9B6LL63RGIRl9YO5cIs9hhQTGvgIcb88m0RdZyqacwKAiRUR8UP+lasyMOMMVVY1Pz++EDOArdDHAtdB8/lg7pBu8qZ3fKlGGhFlJ4fu9w9tIZBdAVmKKJpD/9CUkZXWaEoLLncYT29vi5fHUZY112V3WT6jWkAyngQNmjJyRcIkSM7UHnmnnzwu8Gvt/SIcX7zQDVwuOkxiiWDHTZ4+98yTucrCpn/y2+5IPiKdGoNH72Ccs2LiwBgpTjjBz98qmJvvWNdNzeOFe7zaB3WRFPl6bgSWIjhmfPSxea2nJp4kIHtB3OuPs8qFGUQeECtXRkXCxBZ49eog8viBtqT7EMS8G9JUF6IDNWearAAIDv68lcKTKqk0HXwiM/oy99PvGC2rgd6qQZps62flLQQs9t6sTasNgHx6mj+krmGTONeblgu3PtGmCnHRKWsFnNopNcvOwax1rxzmWxfoyzMwjlm+ItUJAA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
